- name: Generic folder structure creation
  file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
    owner: "{{ confluent_user }}"
    group: "{{ confluent_group }}"
  with_items:
    - "{{ confluent_appdir }}"
    - "{{ confluent_appdir }}/bundles"
    - "{{ confluent_appdir }}/etc"

- name: checking if the bundle is present in /tmp directory
  stat: 
     path: "/tmp/{{ confluent_tar_version }}.tar.gz"
  delegate_to: 127.0.0.1
  register: bundle_download_status
  
- name: Download the tar ball from the confluent website
  get_url:
   url: "{{ confluent_package_url }}"
   dest: "/tmp"
  delegate_to: 127.0.0.1
  when: bundle_download_status.stat.exists == false

- name: checking if the bundle is present in confluent bundle directory
  stat: 
     path: "{{ confluent_appdir }}/bundles/{{ confluent_tar_version }}.tar.gz"
  register: confluent_bundle_status

- name: copy the confluent bundle to the location on remote machine
  copy:
    src: "/tmp/{{ confluent_tar_version }}.tar.gz"
    dest: "{{ confluent_appdir }}/bundles/{{ confluent_tar_version }}.tar.gz"
  when: confluent_bundle_status.stat.exists == false

- name: checking if the bundle is extracted in confluent bundle directory
  stat: 
     path: "{{ confluent_appdir }}/bundles/{{ confluent_version }}"
  register: confluent_bundle_extract_status

- name: Extracting the tar ball to bundles location 
  unarchive:
    src: "{{ confluent_appdir }}/bundles/{{ confluent_tar_version }}.tar.gz"
    dest: "{{ confluent_appdir }}/bundles/"
    remote_src: yes
  when: confluent_bundle_extract_status.stat.exists == false

- name: Symlinks for the confluent bin directory
  file:
    state: link
    src: "{{ confluent_appdir }}//bundles/{{ confluent_version }}/bin"
    dest: "{{ confluent_appdir }}/bin"

- name: Symlinks for the confluent plugin directory
  file:
    state: link
    src: "{{ confluent_appdir }}//bundles/{{ confluent_version }}/share/java"
    dest: "{{ confluent_appdir }}/plugins"

- name: Copy profile file
  template:
    src: bash_profile
    dest: "{{ confluent_user_home }}/.bash_profile"
    mode: 0400
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"